apps/administration/urls.py
from django.urls import path
from . import views

app_name='administration'

urlpatterns = [
    path('branch/', views.branches_index, name='branch_index'),
    path('members/', views.members_index, name='members_index'),
    path('outgoingmails/', views.outgoingmails_index, name='outgoingmails_index'),
    path('outgoingmails/add/', views.outgoingmails_add, name='outgoingmails_add'),
    path('incomingmails/', views.incomingmails_index, name='incomingmails_index'),
]

config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from config.settings.base import BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisegu.guest.landingpage.urls', namespace='landing_page')),
    path('employee/', include('sisegu.employee.dashboard.urls', namespace='dashboard')),
    path('employee/', include('sisegu.employee.administration.urls', namespace='administration')),
]+ static(settings.STATIC_URL, document_root=os.path.join(BASE_DIR, 'static'))

sisegu/apps/employee/administration/models.py
from django.db import models
from django.db.models import SET_NULL
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.conf import settings

# Tier Mapping
class Tier(models.IntegerChoices):
    SISWA_M1 = 1, 'Siswa Melati 1'
    SISWA_M2 = 2, 'Siswa Melati 2'
    SISWA_M3 = 3, 'Siswa Melati 3'
    SISWA_M4 = 4, 'Siswa Melati 4'
    KADER_D = 5, 'Kader Dasar'
    KADER_M1 = 6, 'Kader Muda'
    KADER_M2 = 7, 'Kader Madya'
    KADER_M3 = 8, 'Kader Kepala'
    KADER_M4 = 9, 'Kader Utama'
    PENDEKAR_M1 = 10, 'Pendekar Muda'
    PENDEKAR_M2 = 11, 'Pendekar Madya'
    PENDEKAR_M3 = 12, 'Pendekar Kepala'
    PENDEKAR_M4 = 13, 'Pendekar Utama'
    PENDEKAR_M5 = 14, 'Pendekar Besar'

# Mail type mapping
class MailType(models.IntegerChoices):
    UNDANGAN = 1, 'Undangan'
    SK = 2, 'Surat Keputusan'
    PERINTAH = 3, 'Surat Perintah'
    PERMOHONAN = 4, 'Surat Permohonan'
    PEMBERITAHUAN = 5, 'Surat Pemberitahuan'
    PROPOSAL = 6, 'Proposal'
    PEMINJAMAN= 7, 'Surat Peminjaman'


# Branches Model.
class Branches(models.Model):
    name = models.CharField(max_length=70)
    address = models.TextField()
    phone_number = PhoneNumberField(region='ID') # Indonesia
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null = True)

    class Meta:
        verbose_name_plural="Branches"

    def __str__(self):
        return self.name #menampilkan nama


# members model
class Members(models.Model):
    name = models.CharField(max_length=150)
    birth_date = models.DateField()
    branch = models.ForeignKey(Branches, on_delete=models.SET_NULL, null=True)
    tier = models.IntegerField(choices=Tier.choices, default=Tier.SISWA_M1)
    years_of_joining = models.CharField(max_length=4, null=False, blank=False)

    class Meta:
        verbose_name="Member"

    def __str__(self):
        return self.name #menampilkan nama


# mails model
class OutgoingMail(models.Model):
    mail_type = models.IntegerField(choices=MailType.choices, default=MailType.UNDANGAN)
    mail_number = models.CharField(max_length=50, blank=True)
    subject = models.CharField(max_length=150, blank=False)
    recipient = models.CharField(max_length=150, blank=True)
    event_name = models.CharField(max_length=150, blank=False)
    event_location = models.CharField(max_length=150, blank=True, )
    event_Date = models.DateTimeField(null=True, blank=True) # perlu ubah Date menjadi date
    signed_by=models.CharField(max_length=80, blank=False)
    signed_date=models.DateField(null=False, blank=False)
    created_date=models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural='Outgoing Mails'


    def __str__(self):
        return self.subject #menampilkan subjek surat

class IncomingMail(models.Model):
    mail_type = models.IntegerField(choices=MailType.choices, default=MailType.UNDANGAN)
    mail_number = models.CharField(max_length=50, blank=True)
    mail_purpose = models.TextField(blank=True)
    sender = models.CharField(max_length=150, blank=False)
    created_date=models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural = 'Incoming Mails'
    
    def __str__(self):
        return self.sender #menampilkan pengirim surat

templates/outgoingmails/index.html
{% extends "_base.html" %}
{% block title %}Administrasi{% endblock %}

{% block content %}
<!-- Page Heading -->
<h1 class="text-2xl font-semibold">Manajemen Administrasi</h1>


<!-- toast message -->
{% if messages %}
<div id="toast-success" class="fixed top-5 right-5 flex items-center w-full max-w-xs p-2 mb-2 text-gray-500 bg-white rounded-lg shadow-sm space-x-4 " role="alert">
    <div class="inline-flex items-center justify-center shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg ">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
        </svg>
        <span class="sr-only">Check icon</span>
    </div>
    {% for message in messages %}
    <div class="ms-3 text-sm font-normal">{{ message }}</div>
    {% endfor %}
    <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8" data-dismiss-target="#toast-success" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
    </button>
</div>
{% endif %}


<!-- Tabs -->
<div class="text-sm font-medium text-center text-gray-500 border-b mt-5 border-gray-200">
    <ul class="flex flex-wrap -mb-px">
        <li class="me-2">
            <a href="#" class="inline-block p-4 text-red-600 border-b-2 border-red-600 rounded-t-lg " aria-current="page">Surat Keluar</a>
        </li>
        <li class="me-2">
            <a href="/incomingmails" class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300">Surat Masuk</a>
        </li>
    </ul>
</div>

<div class="grid grid-cols-1 py-4 md:grid-cols-3 gap-2 ">
    <div>   
        <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
        <div class="relative">
            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
            </div>
            <input type="search" id="search" class="block w-full p-2.5 ps-10 text-xs text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 " placeholder="Cari nomor surat" required />
            <button type="submit" class="text-white absolute end-2.5 bottom-1.5 bg-yellow-400 hover:bg-yellow-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-xs px-4 py-1">Cari</button>
        </div>
    </div>
    <div">
    <a href="{% url 'administration:outgoingmails_add' %}">
        <button type="button" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-xs px-5 py-2.5">Buat Surat</button>
    </a>
    </div>
</div>

<!-- table -->
<div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-blue-50">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Nomor Surat
                </th>
                <th scope="col" class="px-6 py-3">
                    Jenis Surat
                </th>
                <th scope="col" class="px-6 py-3">
                    Perihal
                </th>
                <th scope="col" class="px-6 py-3">
                    Kepada
                </th>
                <th scope="col" class="px-6 py-3">
                    Tanggal Dibuat
                </th>
            </tr>
        </thead>
        <tbody>
            {% for outmail in outgoingmails %}
            <tr class="bg-white border-b border-gray-200">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {{ outmail.mail_number }}
                </th>
                <td class="px-6 py-4">
                    {{ outmail.get_mail_type_display }}
                </td>
                <td class="px-6 py-4">
                    {{ outmail.subject }}      
                </td>
                <td class="px-6 py-4">
                    {{ outmail.recipient }}
                </td>
                <td class="px-6 py-4">
                    {{ outmail.created_date }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock content %}