apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.index_view, name='dashboard'),
    path('logout', views.logout_view, name='logout')
]

config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from config.settings.base import BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisegu.guest.landingpage.urls', namespace='landing_page')),
    path('employee/', include('sisegu.employee.dashboard.urls', namespace='dashboard')),
    path('employee/', include('sisegu.employee.administration.urls', namespace='administration')),
]+ static(settings.STATIC_URL, document_root=os.path.join(BASE_DIR, 'static'))

sisegu/guest/landingpage/urls.py
from django.urls import path
from sisegu.guest.landingpage import views

app_name='landinng_page'

urlpatterns = [
    path('', views.index, name='index'),
]

sisegu/guest/landingpage/forms.py
from django import forms
from sisegu.apps.employee.administration.models import Branches, Members, OutgoingMail, IncomingMail


INPUT_CLASS = 'block w-full p-2 text-xs text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500'

class AddOutgoingMailForm(forms.ModelForm):
    class Meta:
        model = OutgoingMail
        fields = (
            'mail_type',
            'mail_number',
            'subject',
            'recipient',
            'event_name',
            'event_location',
            'event_Date', #perlu ubah Date menjadi date
            'signed_by',
            'signed_date',
            )
        widgets={
            'mail_type': forms.Select(attrs={
                'class':f"{INPUT_CLASS} mb-4",
                'id':'small',
                'name':'mail_type',
            }),
            'mail_number': forms.TextInput(attrs={
                'type':'text',
                'class': INPUT_CLASS,
                'id':'small-input',
                'name':'mail_number',
                'required':'required',
            }),
            'subject': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'subject',
                'required':'required',
            }),
            'recipient': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'recipient',
                'required':'required',
            }),
            'event_name': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_name',
            }),
            'event_location': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_location',
                'required':'required',
            }),
            'event_Date': forms.TextInput(attrs={
                'type':'date',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_Date',
                'required':'required',
            }),
            'signed_by': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'signed_by',
            }),
            'signed_date': forms.TextInput(attrs={
                'type':'date',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'signed_date',
            }),
        }

sisegu/guest/landingpage/views.py
from django.utils import timezone
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from sisegu.apps.employee.administration.models import Branches, Members, OutgoingMail, IncomingMail
from .forms import AddOutgoingMailForm

# Landing Page
def index(request):
    return render(request, 'guest/index.html')

templates/guest/_base.html
{% load compress %} 
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Dashboard{% endblock %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
    {% block extra_css %}
    {% endblock %}
  </head>
  <body class="bg-red-800">
    {% block content %}
    {% endblock %}
    <!-- flowbite js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
  </body>
</html>

templates/guest/index.html
{% extends "guest/_base.html" %}
{% load static %}
{% block title %}Tapak Suci Balikpapan{% endblock %}


{% block content %}
<nav class="bg-red-700 fixed w-full z-20 top-0 start-0 border-white shadow-lg">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'img/tspng.png' %}" class="h-14" alt="Flowbite Logo" />
        </a>
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <a href="{% url 'dashboard:login' %}">
                <button type="button" class="text-red-600 bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-bold rounded-lg text-sm px-4 py-2 text-center">Login</button>
            </a>
            <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-white rounded-lg md:hidden focus:outline-none focus:ring-2" aria-controls="navbar-cta" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-white rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent">
                <li>
                    <a href="#" class="block py-2 px-3 md:p-0 text-white bg-yellow-500 rounded-sm md:bg-transparent md:text-yellow-400" aria-current="page">Home</a>
                </li>
                <li>
                    <a href="#" class="block py-2 px-3 md:p-0 text-white rounded-sm md:hover:bg-transparent md:hover:text-yellow-400">About</a>
                </li>
                <li>
                    <a href="#" class="block py-2 px-3 md:p-0 text-white rounded-sm md:hover:bg-transparent md:hover:text-yellow-400">Services</a>
                </li>
                <li>
                    <a href="#" class="block py-2 px-3 md:p-0 text-white rounded-sm md:hover:bg-transparent md:hover:text-yellow-400">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="mt-20 md:mt-10">
    <img class="h-auto max-w-full" src="{% static 'img/bg.jpg' %}" alt="Jumbotron"/>
    <div class="absolute -mt-5 md:-mt-20">
        <img class="max-w-full" src="{% static 'img/sabuk 2.png' %}" alt="sabuk">
    </div>
</div>


{% endblock %}