config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from config.settings.base import BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisegu.guest.landingpage.urls', namespace='landing_page')),
    path('employee/', include('sisegu.employee.dashboard.urls', namespace='dashboard')),
    path('employee/', include('sisegu.employee.administration.urls', namespace='administration')),
]+ static(settings.STATIC_URL, document_root=os.path.join(BASE_DIR, 'static'))

sisegu/employee/administration/urls.py
from django.urls import path
from sisegu.employee.administration import views

app_name='administration'

urlpatterns = [
    path('branch/', views.branches_index, name='branch_index'),
    path('members/', views.members_index, name='members_index'),
    path('outgoingmails/', views.outgoingmails_index, name='outgoingmails_index'),
    path('outgoingmails/add/', views.outgoingmails_add, name='outgoingmails_add'),
    path('outgoingmails/<int:id>', views.outgoingmails_detail, name='outgoingmails_detail'),
    path('incomingmails/', views.incomingmails_index, name='incomingmails_index'),
]

sisegu/employee/dashboard/urls.py
from django.urls import path
from sisegu.employee.dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.index_view, name='index'),
    path('logout', views.logout_view, name='logout')
]

sisegu/apps/employee/administration/models.py
from django.db import models
from django.db.models import SET_NULL
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.conf import settings

# Tier Mapping
class Tier(models.IntegerChoices):
    SISWA_M1 = 1, 'Siswa Melati 1'
    SISWA_M2 = 2, 'Siswa Melati 2'
    SISWA_M3 = 3, 'Siswa Melati 3'
    SISWA_M4 = 4, 'Siswa Melati 4'
    KADER_D = 5, 'Kader Dasar'
    KADER_M1 = 6, 'Kader Muda'
    KADER_M2 = 7, 'Kader Madya'
    KADER_M3 = 8, 'Kader Kepala'
    KADER_M4 = 9, 'Kader Utama'
    PENDEKAR_M1 = 10, 'Pendekar Muda'
    PENDEKAR_M2 = 11, 'Pendekar Madya'
    PENDEKAR_M3 = 12, 'Pendekar Kepala'
    PENDEKAR_M4 = 13, 'Pendekar Utama'
    PENDEKAR_M5 = 14, 'Pendekar Besar'

# Mail type mapping
class MailType(models.IntegerChoices):
    UNDANGAN = 1, 'Undangan'
    SK = 2, 'Surat Keputusan'
    PERINTAH = 3, 'Surat Perintah'
    PERMOHONAN = 4, 'Surat Permohonan'
    PEMBERITAHUAN = 5, 'Surat Pemberitahuan'
    PROPOSAL = 6, 'Proposal'
    PEMINJAMAN= 7, 'Surat Peminjaman'


# Branches Model.
class Branches(models.Model):
    name = models.CharField(max_length=70)
    address = models.TextField()
    phone_number = PhoneNumberField(region='ID') # Indonesia
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null = True)

    class Meta:
        verbose_name_plural="Branches"

    def __str__(self):
        return self.name #menampilkan nama


# members model
class Members(models.Model):
    name = models.CharField(max_length=150)
    birth_date = models.DateField()
    branch = models.ForeignKey(Branches, on_delete=models.SET_NULL, null=True)
    tier = models.IntegerField(choices=Tier.choices, default=Tier.SISWA_M1)
    years_of_joining = models.CharField(max_length=4, null=False, blank=False)

    class Meta:
        verbose_name="Member"

    def __str__(self):
        return self.name #menampilkan nama


# mails model
class OutgoingMail(models.Model):
    mail_type = models.IntegerField(choices=MailType.choices, default=MailType.UNDANGAN)
    mail_number = models.CharField(max_length=50, blank=True)
    subject = models.CharField(max_length=150, blank=False)
    recipient = models.CharField(max_length=150, blank=True)
    event_name = models.CharField(max_length=150, blank=False)
    event_location = models.CharField(max_length=150, blank=True, )
    event_Date = models.DateTimeField(null=True, blank=True) # perlu ubah Date menjadi date
    signed_by=models.CharField(max_length=80, blank=False)
    signed_date=models.DateField(null=False, blank=False)
    created_date=models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural='Outgoing Mails'


    def __str__(self):
        return self.subject #menampilkan subjek surat

class IncomingMail(models.Model):
    mail_type = models.IntegerField(choices=MailType.choices, default=MailType.UNDANGAN)
    mail_number = models.CharField(max_length=50, blank=True)
    mail_purpose = models.TextField(blank=True)
    sender = models.CharField(max_length=150, blank=False)
    created_date=models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural = 'Incoming Mails'
    
    def __str__(self):
        return self.sender #menampilkan pengirim surat

sisegu/apps/employee/dashboard/models.py
from django.db import models

# Create your models here.

sisegu/employee/administration/forms.py
from django import forms
from sisegu.apps.employee.administration.models import Branches, Members, OutgoingMail, IncomingMail


INPUT_CLASS = 'block w-full p-2 text-xs text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500'

class AddOutgoingMailForm(forms.ModelForm):
    class Meta:
        model = OutgoingMail
        fields = (
            'mail_type',
            'mail_number',
            'subject',
            'recipient',
            'event_name',
            'event_location',
            'event_Date', #perlu ubah Date menjadi date
            'signed_by',
            'signed_date',
            )
        widgets={
            'mail_type': forms.Select(attrs={
                'class':f"{INPUT_CLASS} mb-4",
                'id':'small',
                'name':'mail_type',
            }),
            'mail_number': forms.TextInput(attrs={
                'type':'text',
                'class': INPUT_CLASS,
                'id':'small-input',
                'name':'mail_number',
                'required':'required',
            }),
            'subject': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'subject',
                'required':'required',
            }),
            'recipient': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'recipient',
                'required':'required',
            }),
            'event_name': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_name',
            }),
            'event_location': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_location',
                'required':'required',
            }),
            'event_Date': forms.DateTimeInput(
                attrs={
                'type':'datetime-local',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'event_Date',
                'required':'required',
                },
                format='%Y-%m-%dT%H:%M'
            ),
            'signed_by': forms.TextInput(attrs={
                'type':'text',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'signed_by',
            }),
            'signed_date': forms.TextInput(attrs={
                'type':'date',
                'class':INPUT_CLASS,
                'id':'small-input',
                'name':'signed_date',
            }),
        }

sisegu/employee/administration/views.py
from django.utils import timezone
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from sisegu.apps.employee.administration.models import Branches, Members, OutgoingMail, IncomingMail
from .forms import AddOutgoingMailForm

# Branches
@login_required
def branches_index (request):
    #get all branch
    branches = Branches.objects.all()
    return render(request, 'employee/branches/index.html', {'branches':branches})

# Members
@login_required
def members_index (request):
    #get all members
    members = Members.objects.all()
    return render(request, 'employee/members/index.html', {'members':members})


# mails
@login_required
def outgoingmails_index(request):
    #get all ougoing mails
    outgoingmails = OutgoingMail.objects.all()
    context = {
        'outgoingmails': outgoingmails,
        'current_tab': 'outgoingmails'
    }
    return render(request, 'employee/mails/outgoingmails/index.html', context)

@login_required
def outgoingmails_add(request):
    if request.method == 'POST':
        #get form data
        outgoingmail_form = AddOutgoingMailForm(request.POST)
        #check if form is valid
        if outgoingmail_form.is_valid():
            #save form data to database
            new_outgoingmail = outgoingmail_form.save(commit=False)
            new_outgoingmail.created_by=request.user
            new_outgoingmail.create_date = timezone.now()
            new_outgoingmail.save()
            #show success message
            messages.success(request,'Anda Berhasil Membuat Surat')
            return redirect('administration:outgoingmails_index')
        else:
            messages.error(request, 'Form tidak valid. Periksa kembali input Anda.')
    else:
        outgoingmail_form = AddOutgoingMailForm()
            
    return render(request, 'employee/mails/outgoingmails/add_new.html',{'form': outgoingmail_form})

@login_required
def outgoingmails_detail(request, id):
    #get outgoing mail by id
    detail = get_object_or_404(OutgoingMail, id=id)
    context = {
        'detail':detail,
    }
    return render(request, 'employee/mails/outgoingmails/details.html',context)

@login_required
def incomingmails_index(request):
    #get all ougoing mails
    incomingmails = IncomingMail.objects.all()
    context = {
        'incomingmails': incomingmails,
        'current_tab': 'incomingmails'

    }
    return render(request, 'employee/mails/incomingmails/index.html',context)

sisegu/employee/dashboard/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def login_view(request):
    error_message = None
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    if request.method == 'POST':
        authform = AuthenticationForm(request, data=request.POST)
        if authform.is_valid():
            login(request, authform.get_user())
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('dashboard:index')
        else:
            error_message = 'Username atau password yang anda masukkan salah!'
    else:
        authform = AuthenticationForm()
    return render(request,'employee/login.html',{'form':authform, 'error':error_message})


@login_required
def index_view(request):
    return render(request, 'employee/dashboard/index.html',{})


def logout_view(request):
    logout(request)
    return redirect('dashboard:login')

templates/employee/_base.html
{% load compress %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Dashboard{% endblock %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
  </head>

  <body>
    <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
      <span class="sr-only">Open sidebar</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
      </svg>
    </button>
    <aside id="logo-sidebar" class="fixed top-0 left-0 shadow-lg z-40 w-55 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
      <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50">
          <a href="#" class="flex items-center ps-2.5 mb-5">
            <img src="https://2.bp.blogspot.com/-ociusXJxs6s/Wg0i1c75RVI/AAAAAAAAE_Q/qjLtSi8GEy02XVPrC-__-dSK1YEqT7aPQCLcBGAs/s1600/Tapak%2BSUci.png" class="h-6 me-3 sm:h-7" alt="Sisegu Logo" />
            <span class="self-center text-xl font-bold text-red-500">SISEGU</span>
          </a>
          {% block sidebar %}
          <ul class="space-y-2 font-medium">
            <li>
                <a href="{% url 'dashboard:index' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                  <svg class="w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                      <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                      <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
                  </svg>
                  <span class="ms-3">Dashboard</span>
                </a>
            </li>
            <li>
              <span class="font-light text-sm">Administrasi</span> <!-- grouping menu-->
            </li>
            <li>
              <a href="{% url 'administration:outgoingmails_index' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 8v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8m18 0-8.029-4.46a2 2 0 0 0-1.942 0L3 8m18 0-9 6.5L3 8"/>
                </svg>                 
                <span class="flex-1 ms-3 whitespace-nowrap">Manajemen Surat</span>
              </a>
            </li>
            <li>
              <a href="{% url 'administration:members_index' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 9h3m-3 3h3m-3 3h3m-6 1c-.306-.613-.933-1-1.618-1H7.618c-.685 0-1.312.387-1.618 1M4 5h16a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Zm7 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
                </svg>                                   
                <span class="flex-1 ms-3 whitespace-nowrap">Keanggotaan</span>
              </a>
            </li>
            <li>
              <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6h8m-8 6h8m-8 6h8M4 16a2 2 0 1 1 3.321 1.5L4 20h5M4 5l2-1v6m-2 0h4"/>
                </svg>                                                 
                <span class="flex-1 ms-3 whitespace-nowrap">Prestasi</span>
              </a>
            </li>
            <li>
              <a href="{% url 'administration:branch_index' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linejoin="round" stroke-width="1.5" d="m7.14284 11 4.99996-6 5 6m-9.99996 0h-3v8H20.1428v-8h-3m-9.99996 0H3.14285l3-4h4.33735l-3.33736 4Zm9.99996 0h4l-3-4h-4.3374l3.3374 4Zm-3 2c0 1.1046-.8954 2-2 2-1.1045 0-2-.8954-2-2s.8955-2 2-2c1.1046 0 2 .8954 2 2Z"/>
                </svg>                                                  
                <span class="flex-1 ms-3 whitespace-nowrap">Cabang Latihan</span>
              </a>
            </li>
            <li>
              <span class="font-light text-sm">Event</span> <!-- grouping menu-->
            </li>
            <li>
              <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                  <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7h1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h11.5M7 14h6m-6 3h6m0-10h.5m-.5 3h.5M7 7h3v3H7V7Z"/>
                  </svg>
                                  
                  <span class="flex-1 ms-3 whitespace-nowrap">UKT</span>
                </a>
            </li>
            <li>
              <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-width="1.5" d="M11.083 5.104c.35-.8 1.485-.8 1.834 0l1.752 4.022a1 1 0 0 0 .84.597l4.463.342c.9.069 1.255 1.2.556 1.771l-3.33 2.723a1 1 0 0 0-.337 1.016l1.03 4.119c.214.858-.71 1.552-1.474 1.106l-3.913-2.281a1 1 0 0 0-1.008 0L7.583 20.8c-.764.446-1.688-.248-1.474-1.106l1.03-4.119A1 1 0 0 0 6.8 14.56l-3.33-2.723c-.698-.571-.342-1.702.557-1.771l4.462-.342a1 1 0 0 0 .84-.597l1.753-4.022Z"/>
                  </svg>
                  
                  <span class="flex-1 ms-3 whitespace-nowrap">Kejuaraan</span>
                </a>
              </li>
              <li>
                <span class="font-light text-sm">Settings</span> <!-- grouping menu-->
              </li>
              <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                  <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="1.5" d="M10 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h2m10 1a3 3 0 0 1-3 3m3-3a3 3 0 0 0-3-3m3 3h1m-4 3a3 3 0 0 1-3-3m3 3v1m-3-4a3 3 0 0 1 3-3m-3 3h-1m4-3v-1m-2.121 1.879-.707-.707m5.656 5.656-.707-.707m-4.242 0-.707.707m5.656-5.656-.707.707M12 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                  </svg>                  
                  <span class="flex-1 ms-3 whitespace-nowrap">Manajemen Akun</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'dashboard:logout' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                  <svg class="w-6 h-6 text-gray-500 group-hover:text-gray-900" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 12H8m12 0-4 4m4-4-4-4M9 4H7a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h2"/>
                  </svg>                  
                  <span class="flex-1 ms-3 whitespace-nowrap">Keluar</span>
                </a>
            </li>
          </ul>
          {% endblock %}
        </div>
        </aside>
    <div class="p-4 sm:ml-64">
      <div class="p-4 border-gray-200 rounded-lg">
        {% block content %} {% endblock %}
      </div>
    </div>

    <!-- flowbite js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
  </body>
</html>

templates/employee/login.html
{% load compress %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Dashboard{% endblock %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
  </head>
  <body>
    <form method="POST">
        {% csrf_token %}
        <div class="max-w-md mx-auto p-5 mt-20">
            <img class="w-50 mx-auto md:w-40" src="{% static 'img/tspng.png' %}" alt="Logo">
            <h1 class="text-3xl font-bold mb-5">Login</h1>
            <div class="mb-5">
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Username</label>
                {{ form.username }}    
            </div>
            <div class="mb-5">
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900">Password</label>
                {{ form.password }}    
            </div>
            {% if error %}
            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50" role="alert">
              <svg class="shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
              </svg>
              <span class="sr-only">Info</span>
              <div>
                <span class="font-medium">Gawat!</span> <br> {{ error }}
              </div>
            </div>
            {% endif %}
            <button type="submit" class="mt-3 text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full px-5 py-2.5 text-center">Submit</button>
          </div>
        </form>
    <!-- flowbite js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
  </body>
</html>